version : '3.8'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3308:3306
    volumes:
      - ./scripts_mysql/:/docker-entrypoint-initdb.d/
